### PR TITLE
add user config

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud

### CODE REVIEW

**Comment by wlan0** [comment]
@ibuildthecloud -- it doesnt support clear text password. it only supports hashed passwords, like in CoreOS and Cloud-Init

**Comment by wlan0** [comment]
@ibuildthecloud  -- it doesn't support clear text passwords, it only supports hashed passwords.

**Comment by wlan0** [comment]
@ibuildthecloud updated the code

**Comment by ibuildthecloud** [comment]
@wlan0 What is a test cloud-config that you've used?  I tested this and couldn't get it to work.  Can you also rebase.

**Comment by wlan0** [comment]
@ibuildthecloud  cloud init was changed after i made this PR

Just had to bind mount in user-volumes to get it to work.

**Pull request closed without merging**
