### PR TITLE
VirtualBox convenience scripts

### PR DESCRIPTION
**Pull request by imikushin**
VirtualBox convenience scripts

### CODE REVIEW

**Comment by cloudnautique** [comment]
Thanks for the pull request! I'm curious about your use case for these scripts. We initially added them just to quickly test booting the ISO while developing.
 
Are you using them for something else? We have a Vagrant box that we publish [rancherio/os-vagrant](https://github.com/rancherio/os-vagrant)

**Comment by imikushin** [comment]
I tried os-vagrant v0.1.1 and v0.1.2. Both times I ended up assembling my own vbox machines with these scripts. On v0.1.1 `lo` interface was broken, on v0.1.2 it's rancherio/os-vagrant#8. 

The vagrant box is just a binary blob (though I guess there is a packer config somewhere), so I send my patches here so you notice them.

**Comment by cloudnautique** [comment]
@imikushin I'd like to get the updates you made to the main VM create stuff in the build-vbox-vm script. Given that the main use case for these is to quickly spin up a vbox vm, would you feel comfortable dumping the extra NIC configuration? I'm thinking we just do SATA/virtio/VMDK stuff. Thoughts? If there are use cases I'm not thinking of can totally be swayed.

**Comment by imikushin** [comment]
@cloudnautique sorry for replying late. I added the extra NIC and host-only network configuration to be able to build a version of RancherOS vagrant box that'd have an extra NIC configured with DHCP. At that time this was the only option and it seemed logical to propose this change here. Now that os-vagrant has all this (and more), the extra NIC config here is probably not needed anymore.

**Comment by ibuildthecloud** [comment]
@imikushin @cloudnautique Should this be closed or is there something we should do to merge it?

**Comment by imikushin** [comment]
I'm done with the changes. Feel free to merge :)

**Comment by cloudnautique** [comment]
LGTM

**Comment by ibuildthecloud** [comment]
Done

**Pull request merged**
