### PR TITLE
Added tty, stdinopen, workingdir for system-services

### LINKED ISSUE #220: working_dir: the setting doesn't work with services
v0.3.0

Enabling a service with this yaml code doesn't work:

```yaml
working_dir: /test
```

When I do a docker inspect on the container created with the yaml file, the container doesn't have the working_dir set:

```
"Config": {
      "WorkingDir": ""
}
```

It doesn't appear to be attempted to be set in the code.

### PR DESCRIPTION
**Pull request by deniseschannon**
Fixes #220, #213, #214.

### CODE REVIEW

**Comment by deniseschannon** [comment]
Added .DS_Store in .gitignore based on #231.

**Comment by ibuildthecloud** [comment]
Can you make this change in the refactor branch of rancher-compose

https://github.com/rancherio/rancher-compose/tree/refactor

**Comment by ibuildthecloud** [comment]
Godeps folder is vendored code which means the source is in a different repo that we copy in.  So we don't change anything in Godeps.

**Comment by deniseschannon** [comment]
Closing this PR as I've moved the change into the correct folder.

**Pull request closed without merging**
