### PR TITLE
add ability to delete dynamically added services

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud 
Fixes https://github.com/rancherio/os/issues/191

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Can you add docs on the gh-pages branch for this command

**Comment by wlan0** [comment]
yes, i'll do that

**Comment by wlan0** [comment]
@ibuildthecloud Can this be merged?

@deniseschannon said she'd manually merge in the PR i made for this. Is that done denise?

**Comment by deniseschannon** [comment]
@wlan0 I added in the documentation part so it's already part of the new docs.

**Comment by deniseschannon** [comment]
@ibuildthecloud Question: When I delete the ubuntu-console service and it is enabled, it disables it. No message on the fact that the service cannot be deleted. Basically, the change is removing the enablement from the rancher.yml file code for the services from the os-services directory.

**Comment by deniseschannon** [comment]
@wlan0 spoke with @ibuildthecloud and he's okay with this behavior

**Pull request merged**
