### PR TITLE
etcd and flannel addons

### PR DESCRIPTION
**Pull request by imikushin**
etcd and flannel addons

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
This is really cool.  Thanks.  I will review this as soon as I get the chance.  We for sure would like to support etcd, fannel, and any other popular Docker service as an addon.

**Comment by imikushin** [comment]
I just hope this runs fine.

**Comment by ibuildthecloud** [comment]
@imikushin Should we close this?  As a result of the k8s containers you are working on will we also get a generic etcd and flannel one?

**Comment by imikushin** [comment]
Generic etcd is possible right now (with `quay.io/coreos/etcd:v2.0.10`). Flannel (`quay.io/coreos/flannel:0.4.0`) needs variable substitution in compose to get user configuration or we'll need to repackage it to add wrapper scripts, which is easy to do. So, closing it now.

**Pull request closed without merging**
